# -*- mode: ruby -*-

namespace :mercurial do
  namespace :extensions do
    extensions_rc = "~/.mercurial/extensions.rc".gsub(/~/, ENV['HOME'])
    extensions_dir = "~/.mercurial/extensions".gsub(/~/, ENV['HOME'])
    extensions = [
      %w[https://bitbucket.org/troter/hg-grepfile hg-grepfile grepfile.py grepfile],
      %w[https://bitbucket.org/durin42/hg-git hg-git hggit hggit],
      %w[https://bitbucket.org/sjl/hg-review hg-review review review],
      %w[https://bitbucket.org/peerst/hgcollapse hgcollapse hgext/collapse.py collapse],
      %w[https://bitbucket.org/yujiewu/hgflow hgflow src/hgflow.py flow],
      %w[https://bitbucket.org/durin42/hgsubversion/ hgsubversion hgsubversion hgsubversion],
      %w[https://bitbucket.org/alu/hgtasks hgtasks hgext/tasks.py tasks],
    ]
    extension_dirs = extensions.map do |extension|
      _, name = extension
      File.join(extensions_dir, name)
    end

    directory extensions_dir
    extensions.each do |extension|
      url, name = extension
      file File.join(extensions_dir, name) => extensions_dir do
        cd extensions_dir do
          sh "hg clone #{url} #{name}"
        end
      end
    end

    desc "mercurial extensions install"
    task :install => extension_dirs + [:rc]

    desc "mercurial extensions rc"
    task :rc do
      File.open(extensions_rc, 'w') do |f|
        f.write "# -*- coding:utf-8; mode:conf; -*-\n"
        f.write "# this file is generated by task.rake\n"
        f.write "\n"
        f.write "[extensions]\n"
        extensions.each do |extension|
          _, name, file, entry = extension
          f.write "#{entry} = #{File.join(extensions_dir, name, file)}\n"
        end
      end
    end

    desc "mercurial extensions update"
    task :update do
      extension_dirs.each do |extension_dir|
        if File.exists? extension_dir
          cd extension_dir do
            sh "hg update"
          end
        end
      end
    end
  end
end
