#+TITLE: Emacs config
#+STARTUP: indent
#+PROPERTY: header-args:emacs-lisp :results none

* GC threshold を起動後に戻す
=early-config.org= で持ち上げた閾値を、常用値に戻す。
#+begin_src emacs-lisp
(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 64 1024 1024)
                  gc-cons-percentage 0.1)))
#+end_src

* エンコーディング
#+begin_src emacs-lisp
(set-language-environment "Japanese")
(prefer-coding-system 'utf-8)
#+end_src

* デフォルト値
#+begin_src emacs-lisp
(setq-default
 indent-tabs-mode nil
 tab-width 2
 fill-column 100)

(setq inhibit-startup-screen t
      initial-scratch-message nil
      ring-bell-function 'ignore
      use-short-answers t
      create-lockfiles nil
      backup-by-copying t
      backup-directory-alist
        `(("." . ,(expand-file-name "backup" user-emacs-directory)))
      auto-save-file-name-transforms
        `((".*" ,(expand-file-name "auto-save" user-emacs-directory) t))
      custom-file (expand-file-name "custom.el" user-emacs-directory))

(when (file-exists-p custom-file)
  (load custom-file 'noerror))
#+end_src

* Built-in モード
#+begin_src emacs-lisp
(global-display-line-numbers-mode 1)
(column-number-mode 1)
(show-paren-mode 1)
(electric-pair-mode 1)
(savehist-mode 1)
(save-place-mode 1)
(recentf-mode 1)
(winner-mode 1)
(global-auto-revert-mode 1)
#+end_src

* パッケージ管理（straight.el）
=straight.el= で git ベースのパッケージ管理を行う。=use-package= は straight 経由で取り込み、=straight-use-package-by-default= で全 =use-package= 宣言にデフォルト適用する。

** よく使うコマンド
| コマンド                   | 用途                                                 |
|----------------------------+------------------------------------------------------|
| =straight-pull-all=        | 全パッケージを最新化する                              |
| =straight-rebuild-all=     | Emacs アップグレード後などに全パッケージを再ビルドする |
| =straight-freeze-versions= | lockfile (=straight/versions/default.el=) を書き出す  |
| =straight-thaw-versions=   | lockfile に従ってバージョンを巻き戻す                 |
#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(eval-when-compile (require 'use-package))
(setq straight-use-package-by-default t
      use-package-always-defer t)
#+end_src

* シェル環境変数の取り込み
GUI Emacs（=Emacs.app= 等）を Dock や Spotlight から起動した場合、シェルの =PATH= 等が引き継がれない。=exec-path-from-shell= で起動時にログインシェルから取り込み、ターミナル起動時と動作を揃える。
#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :if (memq window-system '(mac ns x))
  :demand t
  :config (exec-path-from-shell-initialize))
#+end_src

* テーマ
#+begin_src emacs-lisp
(use-package modus-themes
  :demand t
  :config (load-theme 'modus-vivendi t))
#+end_src

* 補完の大文字小文字を無視する
ファイル名・バッファ名・一般補完すべてで case を区別しない。orderless / vertico もこの設定を尊重する。
#+begin_src emacs-lisp
(setq read-file-name-completion-ignore-case t
      read-buffer-completion-ignore-case t
      completion-ignore-case t)
#+end_src

* 補完 UI（vertico + orderless + marginalia + consult + embark）
#+begin_src emacs-lisp
(use-package vertico
  :demand t
  :config (vertico-mode 1))

(use-package orderless
  :demand t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides
   '((file (styles basic partial-completion)))))

(use-package marginalia
  :demand t
  :config (marginalia-mode 1))

(use-package consult
  :bind (("C-s"   . consult-line)
         ("C-x b" . consult-buffer)
         ("M-y"   . consult-yank-pop)
         ("M-g g" . consult-goto-line)
         ("M-g i" . consult-imenu)
         ("M-s r" . consult-ripgrep)))

(use-package embark
  :bind (("C-." . embark-act)
         ("M-." . embark-dwim)))

(use-package embark-consult
  :after (embark consult)
  :hook (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

* バッファ内補完（corfu + cape）
#+begin_src emacs-lisp
(use-package corfu
  :demand t
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  :config (global-corfu-mode 1))

(use-package cape
  :init
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file))
#+end_src

* キーヒント
#+begin_src emacs-lisp
(use-package which-key
  :demand t
  :config (which-key-mode 1))
#+end_src

* Git
#+begin_src emacs-lisp
(use-package magit
  :bind ("C-x g" . magit-status))
#+end_src

* LSP（=M-x eglot= で起動）
=eglot= は Emacs 29 以降に同梱されているため =:straight nil= で built-in 版を使う。
#+begin_src emacs-lisp
(use-package eglot
  :straight nil
  :defer t)
#+end_src

* Tree-sitter（Emacs 29+）
#+begin_src emacs-lisp
(use-package treesit-auto
  :demand t
  :custom (treesit-auto-install 'prompt)
  :config (global-treesit-auto-mode 1))
#+end_src

* Markup
#+begin_src emacs-lisp
(use-package markdown-mode
  :mode (("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode)))

(use-package yaml-mode
  :mode "\\.ya?ml\\'")
#+end_src

* 編集補助
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))
#+end_src
