# -*- coding: utf-8 -*-
# Rakefile for my emacs configration.

require 'rake/clean'

CLEAN.include('**/*~', '**/*.elc')

task :default => :hello

task :hello do
  puts 'Hello!'
end

namespace :info do
  desc "Install info."
  task :install do
    sh 'install-info --info-file=info/elisp-ja.info --info-dir=info'
    sh 'install-info --info-file=info/emacs-lisp-intro-ja.info --info-dir=info'
  end
end

# End of Rakefile.
